import Page from '@wexample/symfony-loader/js/Class/Page';
import Form from '@wexample/symfony-loader/js/Class/Form';
import { assistanceWait } from '@wexample/js-api/Helper/Assistance';
import type { FieldControllerInterface } from '@wexample/js-api/Vue/FieldControllerInterface';

// What the demo agent writes, by field name. It knows the values and nothing
// else: how each one appears is the field's business, which is the whole point
// of the exercise.
const VALUES: Record<string, unknown> = {
  text: 'Maya Lindqvist',
  textarea: '14 Storgatan\n411 38 Göteborg\nSweden',
  email: 'maya@example.com',
  url: 'https://example.com',
  password: 'correct-horse-battery',
  code: '482193',
  number: '34',
  date: '1992-04-17',
  time: '09:30',
  datetime: '2026-10-02T14:00',
  select: 'two',
  radio: 'three',
  switch: true,
  emoji: '🎉',
};

// A file field takes a file and never a name: a name with nothing behind it
// would submit nothing. The demo agent therefore makes a real one, which is
// what an agent fetching or generating a document would hand over.
const demoFile = (): File => new File(
  ['Demo identity document generated by the design system.'],
  'identity.txt',
  { type: 'text/plain' }
);

// Long enough for the eye to follow the halo from one field to the next.
const PAUSE_BETWEEN_FIELDS_MS = 320;

export default class extends Page {
  private isRunning: boolean = false;

  pageReady() {
    this.attach('.assisted-play', () => this.run());
    this.attach('.assisted-reset', () => this.reset());
  }

  private attach(selector: string, onClick: () => void | Promise<void>): void {
    const button = this.el?.querySelector(selector) as HTMLElement | null;

    button?.addEventListener('click', () => {
      void Promise.resolve(onClick());
    });
  }

  // The form holding the gallery. Everything below goes through it, which is
  // the point: the agent names a field and knows nothing else about the page.
  private get form(): Form | undefined {
    return this.components.find((component): component is Form => component instanceof Form);
  }

  private get fields(): FieldControllerInterface[] {
    return this.form?.getFields() ?? [];
  }

  private async run(): Promise<void> {
    if (this.isRunning) {
      return;
    }

    this.isRunning = true;

    try {
      for (const field of this.fields) {
        const value = field.fieldName === 'file' ? demoFile() : VALUES[field.fieldName];

        if (value === undefined) {
          continue;
        }

        // Asked for by name, as an agent would: the demo never reaches for a
        // field it happens to know the shape of.
        await this.form?.getField(field.fieldName)?.setValueAssisted(value);
        await assistanceWait(PAUSE_BETWEEN_FIELDS_MS);
      }
    } finally {
      this.isRunning = false;
    }
  }

  // Empties the gallery so the run can be watched again. Reaching into the
  // controls is a demo liberty: no agent would do this, which is why it lives
  // here and not on the field.
  private reset(): void {
    this.fields.forEach((field) => field.assistanceDeactivate());

    this.el?.querySelectorAll('input, textarea').forEach((element) => {
      if (element instanceof HTMLTextAreaElement) {
        element.value = '';

        return;
      }

      if (!(element instanceof HTMLInputElement)) {
        return;
      }

      if (element.type === 'checkbox' || element.type === 'radio') {
        element.checked = false;
        element.dispatchEvent(new Event('change', { bubbles: true }));

        return;
      }

      if (element.type !== 'hidden' && element.type !== 'submit') {
        element.value = '';
      }
    });
  }
}
