services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Wexample\SymfonyForms\Service\FormProcessor\AbstractFormProcessor:
            tags: ['wexample.symfony_forms.form_processor']

    Wexample\SymfonyDesignSystemDemo\Controller\:
        resource: '../../Controller/'
        exclude: '../../Controller/**/Abstract*.php'
        tags: ['controller.service_arguments']

    Wexample\SymfonyDesignSystemDemo\:
        resource: '../../{EventListener,Form,Repository,Security,Service}'

    Wexample\SymfonyDesignSystemDemo\Api\Controller\:
        resource: '../../Api/Controller/*'
        tags: ['controller.service_arguments']

    Wexample\SymfonyDesignSystemDemo\Api\Normalizer\:
        resource: '../../Api/Normalizer/*'
        tags: ['serializer.normalizer']
